name: gozk-recipes

up:
  - homebrew:
    - zookeeper
  - go:
      version: 1.9
  - railgun

env:
  CGO_CFLAGS: '-I/usr/local/include/zookeeper'
  CGO_LDFLAGS: '-L/usr/local/lib'
  TOXIPROXY_HOST: 192.168.64.87
  TOXIPROXY_URL: http://192.168.64.87:8474
  ZOOKEEPERS: 192.168.64.87:2181

commands:
  test: script/test

packages:
  - git@github.com:Shopify/dev-shopify.git
